name: vhs
on:
    push:
        paths:
            - demo.tape
            - src/**/*.go
    workflow_dispatch: {}
jobs:
    vhs:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v3

            - name: Install Rust toolchain
              uses: dtolnay/rust-toolchain@stable

            - name: Cache
              uses: Swatinem/rust-cache@v2

            - name: Run tests
              run: cargo install --path .

            - name: Setup Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.24"

            - name: Install VHS dependencies
              run: |
                  sudo apt update
                  sudo apt install -y ffmpeg ttyd
                  go install github.com/charmbracelet/vhs@latest

            - name: Generate demo with VHS
              run: vhs demo.tape
              env:
                  TERM: xterm-256color
                  COLORTERM: truecolor

            - uses: stefanzweifel/git-auto-commit-action@v4
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  commit_message: Update generated VHS GIF
                  branch: main
                  commit_user_name: vhs-action
                  commit_user_email: actions@github.com
                  commit_author: vhs-action <actions@github.com>
                  file_pattern: "*.gif"
