name: vhs
on:
    push:
        paths:
            - demo.tape
    workflow_dispatch: {}
jobs:
    vhs:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
            - uses: charmbracelet/vhs-action@v2.1
              with:
                  path: "demo.tape"
            - uses: stefanzweifel/git-auto-commit-action@v4
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  commit_message: Update generated VHS GIF
                  branch: main
                  commit_user_name: vhs-action
                  commit_user_email: actions@github.com
                  commit_author: vhs-action <actions@github.com>
                  file_pattern: "*.gif"
